#!/usr/bin/env python3
r"""
components_table_convert.py
---------------------------
Converts model_training_summary.csv into a LaTeX table grouped by Architecture
with five columns:

    Model | Vision Backbone | Resolution | LLM Backbone | Adaptors and Projectors

Usage:
    python3 components_table_convert.py [input.csv] [output.tex]

Defaults:
    input  -> models/model_training_summary.csv
    output -> models/model_components.tex
"""

import re
import sys
from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
INPUT_CSV = sys.argv[1] if len(sys.argv) > 1 else str(BASE_DIR / "models" / "model_training_summary.csv")
OUTPUT_TEX = sys.argv[2] if len(sys.argv) > 2 else str(BASE_DIR / "models" / "model_components.tex")

ARCHITECTURE_ORDER = [
    "page-to-document encoding models",
    "backbone-centric mllm adaptation",
    "retriever-generator pipeline",
    "agentic pipeline",
]

PREAMBLE = r"""% ─────────────────────────────────────────────────────────────────────────────
% Auto-generated by components_table_convert.py -- do NOT edit manually.
% Re-generate:  python3 components_table_convert.py
%
% Required packages (add to your preamble):
%   \usepackage{booktabs}
%   \usepackage{array}
%   \usepackage{xcolor}
%   \usepackage{colortbl}
%   \usepackage{caption}
%   \usepackage{longtable}
% ─────────────────────────────────────────────────────────────────────────────

\definecolor{sectionbg}{gray}{0.88}

"""


def escape_latex(val):
    if pd.isna(val):
        return "--"
    val = str(val).strip()
    if val in {"", "-"}:
        return "--"
    for char, repl in [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]:
        val = val.replace(char, repl)
    return val


def normalize_architecture(val):
    if pd.isna(val):
        return "uncategorized"
    return re.sub(r"\s+", " ", str(val).strip().lower())


def display_architecture(val):
    labels = {
        "page-to-document encoding models": "Page-to-Document Encoding Models",
        "backbone-centric mllm adaptation": "Backbone-Centric MLLM Adaptation",
        "retriever-generator pipeline": "Retriever-Generator Pipeline",
        "agentic pipeline": "Agentic Pipeline",
        "uncategorized": "Uncategorized",
    }
    return labels.get(val, val.title())


def clean_cell(val):
    """Tidy verbose paper-side phrasing for table display."""
    if pd.isna(val):
        return "-"
    s = str(val).strip()
    if not s or s == "-":
        return "-"
    # Strip leading "N/A (...)" wrappers that explain the absence of a component
    if s.lower().startswith("n/a"):
        inner = re.search(r"\(([^)]*)\)", s)
        if inner:
            inner_text = inner.group(1)
            # Keep only the first model name mentioned (before any verbose clause)
            inner_text = re.sub(r"\s+(consume|consumes|used|use)\s.*", "", inner_text)
            return inner_text.strip()
        return "-"
    # Strip trailing parenthetical clarifications
    s = re.sub(r"\s*\([^)]*\)\s*$", "", s).strip()
    return s


def flatten_summary_headers(df):
    """Flatten the CSV's two-row grouped header (same logic as the training script)."""
    subheaders = df.iloc[0] if not df.empty else None
    flattened = []
    current_group = None

    for raw_col in df.columns:
        col = str(raw_col).strip()
        sub = ""
        if subheaders is not None and pd.notna(subheaders[raw_col]):
            sub = str(subheaders[raw_col]).strip()

        if col.startswith("Unnamed:"):
            if current_group and sub:
                flattened.append(f"{current_group} {sub}")
            else:
                flattened.append(col)
            continue

        if col in {"Vision Encoder", "LLM Backbone", "Adaptors and Projectors"}:
            current_group = col
            if sub:
                flattened.append(f"{col} {sub}")
            else:
                flattened.append(col)
            continue

        if col == "Overall" and sub:
            current_group = col
            flattened.append(f"{col} {sub}")
            continue

        current_group = None
        flattened.append(col)

    work_df = df.copy()
    work_df.columns = flattened
    if not work_df.empty:
        work_df = work_df.iloc[1:].copy()
    return work_df


def read_csv(path):
    df = pd.read_csv(path)
    df = flatten_summary_headers(df)

    required = ["Name", "Architecture",
                "Vision Encoder Name", "Vision Encoder Resolution",
                "LLM Backbone Name", "Adaptors and Projectors Name"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"CSV is missing columns: {missing}")

    df = df[required].copy()
    df = df[df["Name"].notna()].copy()
    df["Name"] = df["Name"].astype(str).str.strip()
    df = df[df["Name"] != ""].copy()
    df["_architecture"] = df["Architecture"].map(normalize_architecture)
    return df


def build_data_rows(df):
    """Render model rows with a light grey rule between adjacent rows in the group."""
    lines = []
    rows = list(df.iterrows())
    for i, (_, row) in enumerate(rows):
        cells = [
            escape_latex(row["Name"]),
            escape_latex(clean_cell(row["Vision Encoder Name"])),
            escape_latex(clean_cell(row["Vision Encoder Resolution"])),
            escape_latex(clean_cell(row["LLM Backbone Name"])),
            escape_latex(clean_cell(row["Adaptors and Projectors Name"])),
        ]
        lines.append("  " + " & ".join(cells) + r" \\")
        if i < len(rows) - 1:
            lines.append(r"  \arrayrulecolor{black!15}\midrule\arrayrulecolor{black}")
    return "\n".join(lines)


def build_table(df):
    work_df = df.copy()
    work_df["_model_sort"] = work_df["Name"].astype(str).str.lower()

    arch_rank = {arch: idx for idx, arch in enumerate(ARCHITECTURE_ORDER)}
    work_df["_arch_rank"] = work_df["_architecture"].map(arch_rank).fillna(len(arch_rank))
    work_df = work_df.sort_values(by=["_arch_rank", "_architecture", "_model_sort"], kind="stable")

    seen_archs = list(dict.fromkeys(work_df["_architecture"].tolist()))
    ordered_archs = [arch for arch in ARCHITECTURE_ORDER if arch in seen_archs]
    ordered_archs.extend(arch for arch in seen_archs if arch not in ordered_archs)

    section_lines = []
    for idx, arch in enumerate(ordered_archs):
        group_df = work_df[work_df["_architecture"] == arch].copy()
        if group_df.empty:
            continue
        if idx > 0:
            section_lines.append(r"\midrule[0.4pt]")
            section_lines.append("")
        label = display_architecture(arch)
        section_lines.append(rf"% -- {label} --")
        section_lines.append(r"\rowcolor{sectionbg}")
        section_lines.append(rf"\multicolumn{{5}}{{l}}{{\textbf{{{escape_latex(label)}}}}} \\")
        section_lines.append(r"\midrule")
        section_lines.append(build_data_rows(group_df))
        section_lines.append("")

    section_block = "\n".join(section_lines).rstrip()

    col_spec = (
        r"l "
        r">{\raggedright\arraybackslash}p{2.4cm} "
        r">{\raggedright\arraybackslash}p{3.2cm} "
        r">{\raggedright\arraybackslash}p{3.5cm} "
        r">{\raggedright\arraybackslash}p{4.2cm}"
    )

    header = (
        r"\textbf{Model} & \textbf{Vision Backbone} & \textbf{Resolution} & "
        r"\textbf{LLM Backbone} & \textbf{Adaptors and Projectors}"
    )

    caption = (
        r"Per-model components of the surveyed MP-VRDU systems grouped by architectural "
        r"family. Resolution lists the input image resolution or page-rendering setting; "
        r"\textit{dynamic} denotes encoders that accept variable-resolution input. "
        r"`--' indicates a component not used by the model."
    )

    return "\n".join([
        r"% -- tab:model_components --",
        r"{",
        r"\scriptsize",
        r"\captionsetup{font=small}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\renewcommand{\arraystretch}{1.1}",
        rf"\begin{{longtable}}{{{col_spec}}}",
        rf"\caption{{{caption}}} \label{{tab:model_components}} \\",
        r"\toprule",
        rf"{header} \\",
        r"\midrule",
        r"\endfirsthead",
        "",
        rf"\multicolumn{{5}}{{l}}{{\textit{{Table \ref{{tab:model_components}} -- continued from previous page}}}} \\",
        r"\toprule",
        rf"{header} \\",
        r"\midrule",
        r"\endhead",
        "",
        rf"\midrule \multicolumn{{5}}{{r}}{{\textit{{Continued on next page}}}} \\",
        r"\endfoot",
        "",
        r"\bottomrule",
        r"\endlastfoot",
        "",
        section_block,
        "",
        r"\end{longtable}",
        r"}",
        "",
    ])


def main():
    df = read_csv(INPUT_CSV)
    table = build_table(df)
    with open(OUTPUT_TEX, "w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write(table)
    print(f"OK  Wrote {OUTPUT_TEX}  ({len(df)} rows, architecture-grouped)")


if __name__ == "__main__":
    main()
