#!/usr/bin/env python3
r"""
open_source_table_convert.py
----------------------------
Converts model_open_source.csv into a LaTeX table listing surveyed MP-VRDU
models that have an open-source GitHub repository.

CSV columns:
    Name, Bibtex, GitHub

Only papers with a non-empty GitHub URL are emitted.

Usage:
    python3 open_source_table_convert.py [input.csv] [output.tex]

Defaults:
    input  -> models/model_open_source.csv
    output -> models/model_open_source.tex
"""

import re
import sys
from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
INPUT_CSV = sys.argv[1] if len(sys.argv) > 1 else str(BASE_DIR / "models" / "model_open_source.csv")
OUTPUT_TEX = sys.argv[2] if len(sys.argv) > 2 else str(BASE_DIR / "models" / "model_open_source.tex")

PREAMBLE = r"""% ─────────────────────────────────────────────────────────────────────────────
% Auto-generated by open_source_table_convert.py -- do NOT edit manually.
% Re-generate:  python3 open_source_table_convert.py
%
% Required packages (add to your preamble):
%   \usepackage{booktabs}
%   \usepackage{array}
%   \usepackage{xcolor}
%   \usepackage{colortbl}
%   \usepackage{caption}
%   \usepackage{url}       % for \url{}
%   \usepackage{natbib}    % for \citeyear (or biblatex)
% ─────────────────────────────────────────────────────────────────────────────

"""


def escape_latex(val):
    if pd.isna(val):
        return ""
    s = str(val).strip()
    if not s:
        return ""
    for ch, repl in [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]:
        s = s.replace(ch, repl)
    return s


def make_model_cell(name, bibtex):
    cell = escape_latex(name)
    key = str(bibtex).strip() if not pd.isna(bibtex) else ""
    if key:
        return rf"{cell}~\citeyear{{{key}}}"
    return cell


def main():
    df = pd.read_csv(INPUT_CSV)
    for col in ("Name", "Bibtex", "GitHub"):
        if col not in df.columns:
            raise ValueError(f"{INPUT_CSV} missing '{col}' column")

    df = df[df["Name"].notna()].copy()
    df["Name"] = df["Name"].astype(str).str.strip()
    df["GitHub"] = df["GitHub"].astype(str).str.strip()
    df = df[(df["Name"] != "") & (df["GitHub"] != "") & (df["GitHub"].str.lower() != "nan")].copy()
    df = df.sort_values(by=df["Name"].str.lower().name, key=lambda s: s.str.lower(), kind="stable")

    rows = []
    for _, row in df.iterrows():
        model_cell = make_model_cell(row["Name"], row.get("Bibtex"))
        url_cell = rf"\url{{{str(row['GitHub']).strip()}}}"
        rows.append("  " + " & ".join([model_cell, url_cell]) + r" \\")

    body = "\n  \\arrayrulecolor{black!15}\\midrule\\arrayrulecolor{black}\n".join(rows)

    col_spec = r"l l"
    header = r"\textbf{Model} & \textbf{GitHub Repository}"

    caption = (
        r"Open-source GitHub repositories released for surveyed MP-VRDU models. "
        r"Only papers that explicitly link a code repository in their text are included."
    )

    table_lines = [
        r"% -- tab:model_open_source --",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\captionsetup{font=small}",
        r"\setlength{\tabcolsep}{6pt}",
        r"\renewcommand{\arraystretch}{1.1}",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        rf"{header} \\",
        r"\midrule",
        "",
        body,
        "",
        r"\bottomrule",
        r"\end{tabular}",
        rf"\caption{{{caption}}}",
        r"\label{tab:model_open_source}",
        r"\end{table}",
        "",
    ]

    with open(OUTPUT_TEX, "w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write("\n".join(table_lines))
    print(f"OK  Wrote {OUTPUT_TEX}  ({len(df)} rows)")


if __name__ == "__main__":
    main()
