#!/usr/bin/env python3
r"""
performance_tables_convert.py
-----------------------------
Converts the survey model performance CSV into two LaTeX tables:
  1. Grouped by architecture category, excluding the OCR column.
  2. Grouped by OCR dependency, excluding the Architecture column.

The model_performance.csv file uses a two-row header, where the first row names
the benchmark and the second row names the metric. This script flattens those
headers internally, then renders them back as two LaTeX heading rows.

Usage:
    python3 performance_tables_convert.py [input.csv] [output_base]

Defaults:
    input       -> model_performance.csv
    output_base -> model_performance
"""

import re
import sys
from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
INPUT_CSV = sys.argv[1] if len(sys.argv) > 1 else str(BASE_DIR / "model_performance.csv")
_out_base = sys.argv[2] if len(sys.argv) > 2 else str(BASE_DIR / "model_performance")
_out_base = _out_base[:-4] if _out_base.endswith(".tex") else _out_base
OUTPUT_ARCH = _out_base + "_arch.tex"
OUTPUT_OCR = _out_base + "_ocr.tex"

DISPLAY_NAME_MAP = {
    "Model": "Model",
    "Variant": "Variant",
}

COLUMN_SPEC_MAP = {
    "Model": "l",
    "Variant": "l",
}

ALWAYS_HIDDEN = {"ID", "Notes"}

PREFERRED_ORDER = [
    "Model",
    "Variant",
    "MP-DocVQA ANLS",
    "DUDE ANLS",
    "LongDocURL Accuracy",
    "MMLongBench Accuracy",
    "MMLongBench F1",
    "MMLongBench-Doc Accuracy",
    "MMLongBench-Doc F1",
    "SlideVQA EM",
    "SlideVQA F1",
]

METRIC_LABELS = {"ANLS", "Accuracy", "F1", "EM"}

ARCH_GROUP_ORDER = [
    "Page-to-Document Transformer",
    "Hierarchical Document Transformer",
    "Backbone-Centric MLLM Adaptation",
    "Retriever-Generator",
    "Agentic Pipeline",
]

OCR_GROUP_LABELS = {
    "No": "OCR-Free",
    "Yes": "OCR-Used",
}
OCR_GROUP_ORDER = ["OCR-Free", "OCR-Used"]
OCR_SORT_ORDER = ["No", "No*", "Yes", "Yes*", "Yes?"]

ARCH_SORT_RANK = {value: idx for idx, value in enumerate(ARCH_GROUP_ORDER)}
OCR_SORT_RANK = {value: idx for idx, value in enumerate(OCR_SORT_ORDER)}

PREAMBLE = r"""% ─────────────────────────────────────────────────────────────────────────────
% Auto-generated by performance_tables_convert.py — do NOT edit manually.
% Re-generate:  python3 performance_tables_convert.py model_performance.csv model_performance
%
% Required packages (add to your preamble):
%   \usepackage{booktabs}
%   \usepackage{array}
%   \usepackage{xcolor}
%   \usepackage{colortbl}
%   \usepackage{caption}
%   \usepackage{adjustbox}
% ─────────────────────────────────────────────────────────────────────────────

\definecolor{sectionbg}{gray}{0.88}

"""


def escape_latex(val):
    """Escape special LaTeX characters in a cell value."""
    if pd.isna(val):
        return "--"
    val = str(val).strip()
    if val in {"", "-"}:
        return "--"
    for char, repl in [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]:
        val = val.replace(char, repl)
    return val


def make_column_config(df_columns, hidden_cols):
    """Infer displayed columns, labels, and column specs from the DataFrame."""
    visible = [col for col in df_columns if col not in hidden_cols]
    ordered = [col for col in PREFERRED_ORDER if col in visible]
    ordered.extend(col for col in visible if col not in ordered)
    config = []
    for col in ordered:
        _, metric = split_benchmark_metric(col)
        default_spec = "c" if metric else "l"
        config.append((col, DISPLAY_NAME_MAP.get(col, col), COLUMN_SPEC_MAP.get(col, default_spec)))
    return config


def split_benchmark_metric(col):
    """Return (benchmark, metric) for flattened benchmark columns."""
    parts = str(col).rsplit(" ", 1)
    if len(parts) == 2 and parts[1] in METRIC_LABELS:
        return parts[0], parts[1]
    return DISPLAY_NAME_MAP.get(col, col), None


def build_header_rows(columns):
    """Render benchmark names on the first heading row and metrics on the second."""
    top_cells = []
    bottom_cells = []
    cmidrules = []
    idx = 0
    table_col = 1

    while idx < len(columns):
        col, header, spec = columns[idx]
        benchmark, metric = split_benchmark_metric(col)
        align = "l" if spec == "l" else "c"

        if metric is None:
            top_cells.append("")
            bottom_cells.append(rf"\textbf{{{escape_latex(header)}}}")
            table_col += 1
            idx += 1
            continue

        start_col = table_col
        span = 1
        metrics = [metric]
        idx += 1
        table_col += 1
        while idx < len(columns):
            next_col = columns[idx][0]
            next_benchmark, next_metric = split_benchmark_metric(next_col)
            if next_benchmark != benchmark or next_metric is None:
                break
            span += 1
            metrics.append(next_metric)
            idx += 1
            table_col += 1

        top_cells.append(rf"\multicolumn{{{span}}}{{{align}}}{{\textbf{{{escape_latex(benchmark)}}}}}")
        bottom_cells.extend(rf"\textbf{{{escape_latex(item)}}}" for item in metrics)
        end_col = start_col + span - 1
        cmidrules.append(rf"\cmidrule(lr){{{start_col}-{end_col}}}")

    return (
        " & ".join(top_cells) + r" \\",
        "".join(cmidrules),
        " & ".join(bottom_cells) + r" \\",
    )


def flatten_metric_headers(df):
    """Flatten the CSV's two-row benchmark metric headers."""
    first_row = df.iloc[0] if not df.empty else None
    columns = list(df.columns)
    flattened = []
    previous_metric = None

    for col in columns:
        header = str(col).strip()
        subheader = ""
        if first_row is not None and pd.notna(first_row[col]):
            subheader = str(first_row[col]).strip()

        if header.startswith("Unnamed:"):
            if previous_metric and subheader:
                flattened.append(f"{previous_metric} {subheader}")
            else:
                flattened.append(header)
            continue

        if subheader in METRIC_LABELS:
            previous_metric = header
            flattened.append(f"{header} {subheader}")
        else:
            previous_metric = header if header not in {"ID", "Model", "OCR", "Architecture", "Variant", "Notes"} else None
            flattened.append(header)

    work_df = df.copy()
    work_df.columns = flattened
    if not work_df.empty:
        metric_marker_cols = [
            col for col in work_df.columns
            if str(work_df.iloc[0].get(col, "")).strip() in METRIC_LABELS
        ]
        if metric_marker_cols:
            work_df = work_df.iloc[1:].copy()
    return work_df


def read_performance_csv(path):
    """Load and normalize model_performance.csv."""
    df = pd.read_csv(path)
    df = flatten_metric_headers(df)
    df = df.loc[:, ~df.columns.astype(str).str.startswith("Unnamed:")]

    required = {"Model", "OCR", "Architecture", "Variant"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV is missing columns: {sorted(missing)}")

    df = df[df["Model"].notna()].copy()
    df = df[df["Architecture"].notna()].copy()
    df["Model"] = df["Model"].astype(str).str.strip()
    df = df[df["Model"] != ""].copy()
    return df


def add_sort_keys(df, group_col):
    """Add stable sort keys for table output."""
    work_df = df.copy()
    unknown_rank = max(len(ARCH_SORT_RANK), len(OCR_SORT_RANK)) + 1

    if group_col == "OCR":
        work_df["_secondary_sort"] = (
            work_df["Architecture"]
            .fillna("")
            .astype(str)
            .str.strip()
            .map(ARCH_SORT_RANK)
            .fillna(unknown_rank)
        )
    else:
        work_df["_secondary_sort"] = (
            work_df["OCR"]
            .fillna("")
            .astype(str)
            .str.strip()
            .map(OCR_SORT_RANK)
            .fillna(unknown_rank)
        )

    work_df["_model_sort"] = work_df["Model"].fillna("").astype(str).str.lower()
    work_df["_variant_sort"] = work_df["Variant"].fillna("").astype(str).str.lower()
    return work_df.sort_values(
        by=["_group", "_secondary_sort", "_model_sort", "_variant_sort"],
        kind="stable",
    )


def make_model_cell(row, show_ocr_asterisk=True):
    name = escape_latex(row["Model"])
    if show_ocr_asterisk and str(row.get("OCR", "")).strip().endswith("*"):
        name += r"$^*$"
    return name


def build_table_rows(df, columns, show_ocr_asterisk=True):
    lines = []
    for _, row in df.iterrows():
        cells = []
        for col, _, _ in columns:
            if col == "Model":
                cells.append(make_model_cell(row, show_ocr_asterisk))
            else:
                cells.append(escape_latex(row.get(col, "")))
        lines.append("  " + " & ".join(cells) + r" \\")
    return "\n".join(lines)


def build_single_table(
    df,
    group_col,
    group_order,
    hidden_cols,
    caption,
    label,
    show_ocr_asterisk=True,
):
    columns = make_column_config(df.columns, hidden_cols)
    col_spec = " ".join(spec for _, _, spec in columns)
    header_top, header_rules, header_bottom = build_header_rows(columns)
    n_cols = len(columns)
    section_span = rf"\multicolumn{{{n_cols}}}{{l}}"

    work_df = df.copy()
    work_df["_group"] = work_df[group_col].fillna("Uncategorized").astype(str).str.strip()
    if group_col == "OCR":
        work_df["_group"] = work_df["_group"].str.rstrip("*?")
        work_df["_group"] = work_df["_group"].map(OCR_GROUP_LABELS).fillna(work_df["_group"])

    work_df = add_sort_keys(work_df, group_col)

    seen_groups = list(dict.fromkeys(work_df["_group"].tolist()))
    ordered_groups = [g for g in group_order if g in seen_groups]
    ordered_groups.extend(g for g in seen_groups if g not in ordered_groups)

    section_lines = []
    for idx, group in enumerate(ordered_groups):
        group_df = work_df[work_df["_group"] == group].copy()
        if group_df.empty:
            continue
        if idx > 0:
            section_lines.append(r"\midrule[0.4pt]")
            section_lines.append("")
        section_lines.append(
            rf"% ── {group} ─────────────────────────────────────────────────────────────"
        )
        section_lines.append(r"\rowcolor{sectionbg}")
        section_lines.append(rf"{section_span}{{\textbf{{{escape_latex(group)}}}}} \\")
        section_lines.append(r"\midrule")
        section_lines.append(build_table_rows(group_df, columns, show_ocr_asterisk))
        section_lines.append("")

    section_block = "\n".join(section_lines).rstrip()
    return "\n".join([
        rf"% ── {label} ──────────────────────────────────────────────────────────────",
        r"\begin{table*}[t]",
        r"\centering",
        r"\scriptsize",
        r"\captionsetup{font=small}",
        r"\setlength{\tabcolsep}{2.5pt}",
        r"\renewcommand{\arraystretch}{0.86}",
        rf"\begin{{adjustbox}}{{width=\textwidth}}",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        header_top,
        header_rules,
        header_bottom,
        r"\midrule",
        "",
        section_block,
        "",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{adjustbox}",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\end{table*}",
        "",
    ])


def main():
    df = read_performance_csv(INPUT_CSV)

    arch_hidden = ALWAYS_HIDDEN | {"Architecture", "OCR"}
    arch_caption = (
        r"Performance of MP-VRDU models grouped by architecture category. "
        r"Reported metrics follow the source papers and are not always directly comparable. "
        r"`--' indicates not reported."
    )
    arch_table = build_single_table(
        df,
        group_col="Architecture",
        group_order=ARCH_GROUP_ORDER,
        hidden_cols=arch_hidden,
        caption=arch_caption,
        label="tab:model_performance_arch",
        show_ocr_asterisk=False,
    )

    with open(OUTPUT_ARCH, "w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write(arch_table)
    print(f"✓  Wrote {OUTPUT_ARCH}  ({len(df)} rows, architecture-grouped)")

    ocr_hidden = ALWAYS_HIDDEN | {"OCR", "Architecture"}
    ocr_caption = (
        r"Performance of MP-VRDU models grouped by OCR usage. "
        r"\textbf{OCR-Used} denotes models that require or incorporate OCR at inference, "
        r"while \textbf{OCR-Free} denotes models that do not require OCR at inference. "
        r"$^*$ next to a model name indicates optional, partial, or training-only OCR usage in the original OCR annotation. "
        r"`--' indicates not reported."
    )
    ocr_table = build_single_table(
        df,
        group_col="OCR",
        group_order=OCR_GROUP_ORDER,
        hidden_cols=ocr_hidden,
        caption=ocr_caption,
        label="tab:model_performance_ocr",
    )

    with open(OUTPUT_OCR, "w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write(ocr_table)
    print(f"✓  Wrote {OUTPUT_OCR}  ({len(df)} rows, OCR-grouped)")


if __name__ == "__main__":
    main()
