#!/usr/bin/env python3
r"""
training_tables_convert.py
--------------------------
Converts model_training.csv into a LaTeX table grouped by the Category column.

The output keeps only:
  - model name
  - Vision Encoder PT/IT/FT states
  - LLM Backbone PT/IT/FT states
  - Adaptor PT/IT/FT states

Training states are normalized as follows:
  - trained -> green check mark
  - frozen  -> red cross
  - -       -> not reported

Usage:
    python3 training_tables_convert.py [input.csv] [output.tex]

Defaults:
    input  -> model_training.csv
    output -> model_training.tex
"""

import re
import sys
from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
INPUT_CSV = sys.argv[1] if len(sys.argv) > 1 else str(BASE_DIR / "model_training.csv")
OUTPUT_TEX = sys.argv[2] if len(sys.argv) > 2 else str(BASE_DIR / "model_training.tex")

COMPONENTS = ["Vision Encoder", "LLM Backbone", "Adaptor"]
STAGES = ["PT", "IT", "FT"]
CATEGORY_ORDER = ["end-to-end", "partial", "training-free / partial", "training-free"]

PREAMBLE = r"""% ─────────────────────────────────────────────────────────────────────────────
% Auto-generated by training_tables_convert.py — do NOT edit manually.
% Re-generate:  python3 training_tables_convert.py model_training.csv model_training.tex
%
% Required packages (add to your preamble):
%   \usepackage{booktabs}
%   \usepackage{array}
%   \usepackage{xcolor}
%   \usepackage{colortbl}
%   \usepackage{caption}
%   \usepackage{amssymb}
% ─────────────────────────────────────────────────────────────────────────────

\definecolor{sectionbg}{gray}{0.88}
\newcommand{\trainmark}{\textcolor{green!60!black}{\ensuremath{\checkmark}}}
\newcommand{\frozenmark}{\textcolor{red!70!black}{\ensuremath{\times}}}

"""


def escape_latex(val):
    """Escape special LaTeX characters in a cell value."""
    if pd.isna(val):
        return "--"
    val = str(val).strip()
    if val in {"", "-"}:
        return "--"
    for char, repl in [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]:
        val = val.replace(char, repl)
    return val


def normalize_category(val):
    """Normalize category strings for stable grouping."""
    if pd.isna(val):
        return "uncategorized"
    return re.sub(r"\s+", " ", str(val).strip().lower())


def display_category(val):
    """Render category labels in a compact title style."""
    labels = {
        "end-to-end": "End-to-End",
        "partial": "Partial",
        "training-free": "Training-Free",
        "training-free / partial": "Training-Free / Partial",
        "uncategorized": "Uncategorized",
    }
    return labels.get(val, val.title())


def normalize_state(val):
    """Map raw training-state text to LaTeX symbols."""
    if pd.isna(val):
        return "--"
    text = str(val).strip().lower()
    text = re.sub(r"\s*\([^)]*\)", "", text).strip()
    if text == "trained":
        return r"\trainmark"
    if text == "frozen":
        return r"\frozenmark"
    if text in {"", "-"}:
        return "--"
    if "trained" in text:
        return r"\trainmark"
    if "frozen" in text:
        return r"\frozenmark"
    return "--"


def flatten_training_headers(df):
    """Flatten the CSV's two-row grouped header."""
    subheaders = df.iloc[0] if not df.empty else None
    flattened = []
    current_group = None

    for raw_col in df.columns:
        col = str(raw_col).strip()
        sub = ""
        if subheaders is not None and pd.notna(subheaders[raw_col]):
            sub = str(subheaders[raw_col]).strip()

        if col.startswith("Unnamed:"):
            if current_group and sub:
                flattened.append(f"{current_group} {sub}")
            else:
                flattened.append(col)
            continue

        if col in COMPONENTS:
            current_group = col
            if sub:
                flattened.append(f"{col} {sub}")
            else:
                flattened.append(col)
            continue

        if col in {"Overall"} and sub:
            current_group = col
            flattened.append(f"{col} {sub}")
            continue

        current_group = None
        flattened.append(col)

    work_df = df.copy()
    work_df.columns = flattened
    if not work_df.empty:
        work_df = work_df.iloc[1:].copy()
    return work_df


def read_training_csv(path):
    """Load and normalize model_training.csv."""
    df = pd.read_csv(path)
    df = flatten_training_headers(df)

    required = {"Name", "Category"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV is missing columns: {sorted(missing)}")

    needed = ["Name", "Category"]
    for component in COMPONENTS:
        for stage in STAGES:
            col = f"{component} {stage}"
            if col not in df.columns:
                raise ValueError(f"CSV is missing column: {col}")
            needed.append(col)

    df = df[needed].copy()
    df = df[df["Name"].notna()].copy()
    df["Name"] = df["Name"].astype(str).str.strip()
    df = df[df["Name"] != ""].copy()
    df["_category"] = df["Category"].map(normalize_category)
    return df


def build_header_rows():
    """Render grouped component headings with PT/IT/FT subcolumns."""
    top = [
        "",
        r"\multicolumn{3}{c}{\textbf{Vision Encoder}}",
        r"\multicolumn{3}{c}{\textbf{LLM Backbone}}",
        r"\multicolumn{3}{c}{\textbf{Adaptor}}",
    ]
    bottom = [r"\textbf{Model}"] + [
        rf"\textbf{{{stage}}}"
        for _ in COMPONENTS
        for stage in STAGES
    ]
    return (
        " & ".join(top) + r" \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}",
        " & ".join(bottom) + r" \\",
    )


def build_data_rows(df):
    """Render model rows for one category."""
    lines = []
    for _, row in df.iterrows():
        cells = [escape_latex(row["Name"])]
        for component in COMPONENTS:
            for stage in STAGES:
                cells.append(normalize_state(row[f"{component} {stage}"]))
        lines.append("  " + " & ".join(cells) + r" \\")
    return "\n".join(lines)


def build_table(df):
    """Build a complete LaTeX table."""
    header_top, header_rules, header_bottom = build_header_rows()
    work_df = df.copy()
    work_df["_model_sort"] = work_df["Name"].astype(str).str.lower()

    category_rank = {cat: idx for idx, cat in enumerate(CATEGORY_ORDER)}
    work_df["_category_rank"] = work_df["_category"].map(category_rank).fillna(len(category_rank))
    work_df = work_df.sort_values(by=["_category_rank", "_category", "_model_sort"], kind="stable")

    seen_categories = list(dict.fromkeys(work_df["_category"].tolist()))
    ordered_categories = [cat for cat in CATEGORY_ORDER if cat in seen_categories]
    ordered_categories.extend(cat for cat in seen_categories if cat not in ordered_categories)

    section_lines = []
    for idx, category in enumerate(ordered_categories):
        group_df = work_df[work_df["_category"] == category].copy()
        if group_df.empty:
            continue
        if idx > 0:
            section_lines.append(r"\midrule[0.4pt]")
            section_lines.append("")
        label = display_category(category)
        section_lines.append(rf"% ── {label} ─────────────────────────────────────────────────────────────")
        section_lines.append(r"\rowcolor{sectionbg}")
        section_lines.append(rf"\multicolumn{{10}}{{l}}{{\textbf{{{escape_latex(label)}}}}} \\")
        section_lines.append(r"\midrule")
        section_lines.append(build_data_rows(group_df))
        section_lines.append("")

    section_block = "\n".join(section_lines).rstrip()

    caption = (
        r"Training status of MP-VRDU model components grouped by training category. "
        r"\trainmark denotes trained parameters, \frozenmark denotes frozen parameters, "
        r"and `--' indicates that the status is not reported or not applicable."
    )

    return "\n".join([
        r"% ── tab:model_training_status ──────────────────────────────────────────────",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\captionsetup{font=small}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\renewcommand{\arraystretch}{0.9}",
        r"\begin{tabular}{l c c c c c c c c c}",
        r"\toprule",
        header_top,
        header_rules,
        header_bottom,
        r"\midrule",
        "",
        section_block,
        "",
        r"\bottomrule",
        r"\end{tabular}",
        rf"\caption{{{caption}}}",
        r"\label{tab:model_training_status}",
        r"\end{table*}",
        "",
    ])


def main():
    df = read_training_csv(INPUT_CSV)
    table = build_table(df)
    with open(OUTPUT_TEX, "w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write(table)
    print(f"✓  Wrote {OUTPUT_TEX}  ({len(df)} rows, category-grouped)")


if __name__ == "__main__":
    main()
